#!/bin/sh
set -e

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

BASE=sso
SSO=/opt/sso/$BASE
SSO_SSD_PIDFILE=/var/run/$BASE-ssd.pid
SSO_LOGFILE=/var/log/$BASE.log

. /lib/lsb/init-functions

if [ -f /etc/default/$BASE ]; then
    . /etc/default/$BASE
fi

case "$1" in
    start)
        touch "$SSO_LOGFILE"
        log_begin_msg "Starting: $BASE"
        start-stop-daemon --start \
            --background \
            --no-close \
            --exec "$SSO" \
            --pidfile "$SSO_SSD_PIDFILE" \
            --make-pidfile \
            >> "$SSO_LOGFILE" 2>&1
        log_end_msg $?
        ;;
    stop)
        log_begin_msg "Stopping: $BASE"
        start-stop-daemon --stop \
            --pidfile "$SSO_SSD_PIDFILE" \
            --retry 10
        log_end_msg $?
        ;;
    restart)
        sso_pid=`cat "$SSO_SSD_PIDFILE" 2>/dev/null`
        [ -n "$sso_pid" ] \
            && ps -p $sso_pid > /dev/null 2>&1 \
            && $0 stop
        $0 start
        ;;
    status)
        status_of_proc -p "$SSO_SSD_PIDFILE" "$SSO" "$BASE"
        ;;
    *)
        echo "Usage: service sso {start|stop|restart|status}"
        exit 1
        ;;
esac
